<a href="https://colab.research.google.com/github/i-rybachok/RybachokMachineLearning/blob/main/%D0%9C%D0%9D_%D0%9B%D0%A01_%D0%A0%D0%B8%D0%B1%D0%B0%D1%87%D0%BE%D0%BA_%D0%A4%D0%86%D0%A24_8_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%8223.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Рибачок Ірина, ФІТ 4-8. На парі була присутня

Лабораторна робота 1.
Вступ до машинного навчання. Елементи лінійної алгебри.

In [ ]:
import numpy as np
np.__version__

'2.0.2'

Task 1

In [ ]:
a = np.random.randint(1,6, size = (3,3))
a

array([[2, 2, 1],
       [1, 4, 3],
       [1, 5, 1]])

Task 2

In [ ]:
det = np.linalg.det(a)
det

np.float64(-17.0)

Task 3

In [ ]:
product = np.prod(a)
product

np.int64(240)

In [ ]:
prod_1=np.prod(a[0])
prod_2=np.prod(a[1])
prod_3=np.prod(a[2])
prod_1*prod_2*prod_3

np.int64(240)

Task 4

In [ ]:
sum_a = np.sum(a)

sum_a

np.int64(20)

Task 5 (Скорочений запис)

In [ ]:
np.max(a)

np.int64(5)

In [ ]:
np.min(a)

np.int64(1)

Task 6 (Скорочений запис)

In [ ]:
#Середнє значення
np.mean(a)

np.float64(2.2222222222222223)

Task 7

In [ ]:
sqrt = np.sqrt(a)
print(sqrt)

[[1.41421356 1.41421356 1.        ]
 [1.         2.         1.73205081]
 [1.         2.23606798 1.        ]]


Task 8

In [ ]:
sum_rows = np.sum(a, axis=1).reshape(-1,1)
print(sum_rows)

[[5]
 [8]
 [7]]


Task 9

In [ ]:
vector = np.random.randint(0, 10, size = 25)
vector

array([3, 0, 6, 5, 8, 5, 1, 1, 0, 9, 3, 1, 4, 9, 4, 7, 5, 0, 4, 0, 6, 5,
       4, 2, 2])

In [ ]:
# Сортування вектора в спадному порядку
sorted_vector=np.sort(vector)[::-1]
sorted_vector

array([9, 9, 8, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 3, 3, 2, 2, 1, 1, 1, 0,
       0, 0, 0])

Task 10

In [ ]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print(mode)
print(median)
print(mean)
print(max_value)
print(min_value)

ModeResult(mode=np.int64(0), count=np.int64(4))
4.0
3.76
9
0


Task 11

In [ ]:
m1=np.random.randint(1,11, size = (4,4))
m1

array([[ 5, 10,  3,  4],
       [ 3,  5,  2,  4],
       [ 9,  8,  3,  4],
       [ 6, 10,  2,  5]])

In [ ]:
m2=np.random.randint(1,11, size = (4,4))
m2

array([[ 1,  6,  9,  9],
       [ 5,  4,  7,  9],
       [ 1,  4,  9,  5],
       [10,  3,  8,  4]])

In [ ]:
m1+m2

array([[ 6, 16, 12, 13],
       [ 8,  9,  9, 13],
       [10, 12, 12,  9],
       [16, 13, 10,  9]])

In [ ]:
m1-m2

array([[ 4,  4, -6, -5],
       [-2,  1, -5, -5],
       [ 8,  4, -6, -1],
       [-4,  7, -6,  1]])

In [ ]:
#Такої операції в лінійній алгебрі не існує
m1*m2

array([[ 5, 60, 27, 36],
       [15, 20, 14, 36],
       [ 9, 32, 27, 20],
       [60, 30, 16, 20]])

In [ ]:
#Такої операції в лінійній алгебрі не існує
m1/m2

array([[5.        , 1.66666667, 0.33333333, 0.44444444],
       [0.6       , 1.25      , 0.28571429, 0.44444444],
       [9.        , 2.        , 0.33333333, 0.8       ],
       [0.6       , 3.33333333, 0.25      , 1.25      ]])

In [ ]:
#Множення матриць
np.dot(m1, m2)

array([[ 98,  94, 174, 166],
       [ 70,  58, 112,  98],
       [ 92, 110, 196, 184],
       [108,  99, 182, 174]])

In [ ]:
#Ділення матриць
np.divide(m1,m2, where = (m2!=0))

array([[5.        , 1.66666667, 0.33333333, 0.44444444],
       [0.6       , 1.25      , 0.28571429, 0.44444444],
       [9.        , 2.        , 0.33333333, 0.8       ],
       [0.6       , 3.33333333, 0.25      , 1.25      ]])

Task 12

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3,3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

Task 13

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1,3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = np.array([1, 2, 3, 2, 2, 3])
x1 = np.arange(6)
x1 ** x2

array([  0,   1,   8,   9,  16, 125])

Task 14

In [ ]:
vector = np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

Task 15

In [ ]:
v1 = np.matrix([1,2,3,4,5])
v1

matrix([[1, 2, 3, 4, 5]])

In [ ]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

Task 16

In [ ]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
v = np.flip(v)
print(v)

[5 4 3 2 1]


Task 17

In [ ]:
np.mean(v)

np.float64(3.0)

Task 18

In [ ]:
np.max(v)

np.int64(5)

In [ ]:
np.min(v)

np.int64(1)

Task 19

In [ ]:
v1 = np.array([1, 2, 3])
v1

array([1, 2, 3])

In [ ]:
v2 = np.array([4, 5, 6])
v2

array([4, 5, 6])

In [ ]:
np.dot(v1, v2)

np.int64(32)

Task 20

In [ ]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
v / norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

Task 21

In [ ]:
# Ортогональні вектори
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
np.dot(v1, v2)

np.int64(0)

Task 22

In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 2, 1])
np.unique(v)

array([1, 2, 3, 4, 5, 6, 7])

Task 23

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
length

np.float64(7.416198487095663)

In [ ]:
np.isclose(length, 5)

np.False_

Task 24

In [ ]:
a = np.random.randint(0, 11, (5, 5))
a

array([[ 0,  8,  1,  9,  5],
       [ 7,  6,  8,  1, 10],
       [ 0,  8,  4,  5,  5],
       [ 5,  9,  8,  9,  0],
       [ 7,  0,  5,  3,  0]])

In [ ]:
np.linalg.det(a)

np.float64(-4240.000000000001)

Task 25

In [ ]:
np.linalg.inv(a)

array([[ 0.22995283,  0.30778302, -0.84551887,  0.34198113, -0.40919811],
       [ 0.15566038,  0.31603774, -0.78773585,  0.46226415, -0.64622642],
       [-0.3254717 , -0.29716981,  0.91981132, -0.33018868,  0.53301887],
       [ 0.00589623, -0.22287736,  0.43985849, -0.24764151,  0.39976415],
       [ 0.00542453, -0.04504717,  0.28466981, -0.22783019,  0.20778302]])

Task 26

In [ ]:
a= np.array([[1, 4, 2], [2, 5, 1], [5, 2, 7]])
b = np.array([5, 9, 2])
x = np.linalg.solve(a, b)
x

array([ 1.4       ,  1.46666667, -1.13333333])

In [ ]:
inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
x1

array([ 1.4       ,  1.46666667, -1.13333333])